# Generated by Django 4.1.5 on 2023-01-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Představení')),
                ('date', models.DateTimeField(verbose_name='Datum')),
                ('venue', models.CharField(max_length=120, verbose_name='Místo konání')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('member_email', models.EmailField(max_length=254, verbose_name='Member Email')),
            ],
        ),
    ]
