# Generated by Django 4.1.5 on 2023-01-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Program',
            new_name='Event',
        ),
    ]
