# Generated by Django 4.1.5 on 2023-01-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_site', '0002_rename_program_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='member_email',
            new_name='user_email',
        ),
        migrations.AddField(
            model_name='event',
            name='tickets',
            field=models.CharField(blank=True, max_length=120, verbose_name='Vstupenky'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Představení'),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=120, verbose_name='Místo konání'),
        ),
    ]
