# Generated by Django 4.1.5 on 2023-01-11 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft_site', '0003_rename_member_email_user_user_email_event_tickets_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Member',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user_email',
            new_name='member_email',
        ),
    ]
