# Generated by Django 4.1.5 on 2023-01-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_site', '0004_rename_user_member_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tickets',
            field=models.URLField(blank=True, max_length=120, verbose_name='Vstupenky'),
        ),
    ]
