# Generated by Django 4.1.5 on 2023-02-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_site', '0006_alter_event_tickets'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStandup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Představení')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('authors', models.TextField(blank=True, verbose_name='Autori')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionTheater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='Představení')),
                ('description', models.TextField(blank=True, verbose_name='Popis')),
                ('authors', models.TextField(blank=True, verbose_name='Autori')),
            ],
        ),
    ]
