# Generated by Django 4.1.5 on 2023-02-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft_site', '0007_productionstandup_productiontheater'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstandup',
            name='fotoPath',
            field=models.TextField(blank=True, verbose_name='Foto'),
        ),
        migrations.AddField(
            model_name='productiontheater',
            name='fotoPath',
            field=models.TextField(blank=True, verbose_name='Foto'),
        ),
    ]
